name: Deploy Lambda

on:
  push:
    paths:
      - 'lambda/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Lambda
        run: |
          cd lambda
          zip function.zip lambda_function.py

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          region: ap-southeast-1
          function_name: your-lambda-name
          zip_file: lambda/function.zip